### ISSUE TITLE
Registro HQ

### ISSUE THREAD

**Issue by daniqs22** [joecha5/dlproyecto3#3]
Modulo que almacena el resultado de la suma o resta, con capacidad de realizar un shift.
Entradas:

- Inicio 0000
- En proceso la entrada sería la salida de sumador o restador
Salida:

- Los 4 bits más significativos del resultado
- Entrada para el sumador o restador

**Comment by daniqs22** [comment]
El issue finaliza una vez se haya creado su respectivo módulo con las entradas y salidas propuestas.
Se espera este listo para el martes 1 de noviembre antes de media noche

**Comment by daniqs22** [comment]
Cuando estoy haciendo el corrimiento no se me está almacenando el bit más significativo

**Comment by sebashm14** [comment]
Perdón por responder hasta ahora pero veo que lo resolvió bien, usando dentro del mismo módulo el valor del bit del dato guardado anteriormente

**Comment by daniqs22** [comment]
El código estuvo listo para la fecha indicada, pero por un error de red no lo subí a tiempo.
